---
title: "éphémère blog"
email: hello@raphaeltm.com
description: |
  A blog about creative media.
baseurl: ''
url: ''
twitter_username: raphaeltm_
markdown: kramdown
timezone: America/Vancouver
paginate: 10
paginate_path: "/page-:num/"
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- vendor
- Gemfile
- Gemfile.lock
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"